### ISSUE TITLE
Support for Swift 2.x?

### ISSUE THREAD

**Issue by craigpearce5** [GabrielAlva/Swift-Prompts#16]
Any timeline on support for Swift 2.x?

**Comment by jlaws** [comment]
+1

**Comment by jlaws** [comment]
It looks like he just needs to release an updated cocoapod.  His change 4 months ago added swift 2 support

**Comment by GabrielAlva** [comment]
Yes, the project is updated to swift 2.0+. Let me know if you have any issues with it and revise it this week, Im pushing an overhaul.

**Comment by jlaws** [comment]
I decided to use another library, but you still may want to update the cocoapod and push it to the cocoapod trunk for users like @craigpearce5

**Comment by GabrielAlva** [comment]
Hi,
I pushed a refactored version of this lib. Please check it out and let me know of any issues or suggest improvements.

**Comment by sydneyitguy** [comment]
@craigpearce5 
pod 'Swift-Prompts', git: 'https://github.com/GabrielAlva/Swift-Prompts'
will solve the problem till they update the cocoapods

**Comment by mohsinka** [comment]
Still getting multiple issues, need an updated version, please. Thanks. 

@jlaws  what lib did you use?

**Comment by jlaws** [comment]
@mohsinka here are the libraries I am using in [Optimize Fitness](http://optimize.fitness).

AKNumericFormatter
Armchair
BFPaperCheckbox
Bolts
Charts
CocoaLumberjack
DateTools
DeviceKit
Doppelganger
DGRunkeeperSwitch
DZNSegmentedControl
FLEX
Haneke
FoldingCell
IQKeyboardManagerSwift
KeyboardController
KeychainAccess
MBProgressHUD
MMAppSwitcher
Material
MaterialControls
Mixpanel
OAuthSwift
PEPhotoCropEditor
Parse
PhoneNumberKit
PromiseKit
RAMAnimatedTabBarController
RMActionController
RMDateSelectionViewController
RMPickerViewController
STZPopupView
SupertopGrid
SwiftString
SwiftyJSON
TextAttributes
Timepiece
TransitionTreasury
UIColor+BFPaperColors

**Comment by XinwenCheng** [comment]
hi @mohsinka , I use your pod line, but seems after pod update finished, source code wasn't downloaded, there're only license and readme files in folder. What should I do? Thanks!

**Comment by XinwenCheng** [comment]
Hi @GabrielAlva , would you please help to check errors I met, thanks!

I'm on Swift 2, and just pod 'Swift-Prompts' in Podfile.
![screen shot 2016-07-09 at 4 11 20 pm](https://cloud.githubusercontent.com/assets/795334/16706967/887470d6-45f2-11e6-9973-03c3d73b6c86.png)
